# config_ovf.yaml

# General
dataset: ovf
tile_size: 128
n_bands: 9
class_weights: [0.121, 0.033, 0.045, 0.090, 0.012, 0.041, 0.020, 0.103, 0.334, 0.010, 0.191]
class_names: ['AB', 'PO', 'MR', 'BF', 'CE', 'PW', 'MH', 'BW', 'SW', 'OR', 'PR']
n_classes: 11
season_map: ["img_s2_2020_spring", "img_s2_2020_summer", "img_s2_2020_fall", "img_s2_2020_winter"]
img_mean: [77.71, 87.54, 77.69, 95.82, 115.36,117.97,119.44,118.58,103.23]
img_std: [56.02, 56.74, 57.51, 57.80, 59.51, 59.12, 57.88, 58.77, 57.07]

# Training parameters
task: regression
pretrained_ckpt: None #tl_logs/test_resnet_decoder/wandblogs/TL-TSC/a2eq467k/checkpoints/epoch=13-step=136346.ckpt
batch_size: 64
max_epochs: 250
optimizer: adamW                 # Options: adam, adamW, sgd
scheduler: cosine         # Options: plateau, steplr, asha, cosine, cosinewarmup
fuse_lr: 0.005
img_lr: 0.005
pc_lr: 0.005
patience: 10
step_size: 10
momentum: 0.9
weight_decay: 0.0001

# Loss weights
weighted_loss: false

# Model architecture
network: ResNet
emb_dims: 768
num_points: 7168
encoder: b                      # Options: s, b, l, xl
fusion_dim: 128
dp_fuse: 0.5
dp_pc: 0.5
use_ms: true
linear_layers_dims: [256, 128]

# Data transforms
image_transform: compose        # Options: compose, random, None
point_cloud_transform: true
rotate: false

# Hardware
gpus: 4