# config_merged.yaml

# General
train_on: ['rmf', 'ovf']                         # Options: rmf, ovf, rmf+ovf
test_on: rmf

# Training parameters
task: regression
max_epochs: 250
optimizer: adamW                 # Options: adam, adamW, sgd
scheduler: cosine         # Options: plateau, steplr, asha, cosine, cosinewarmup
img_lr: 0.0005
pc_lr: 0.0001
fuse_lr: 0.0001
patience: 10
step_size: 10
momentum: 0.9
weight_decay: 0.001

# Loss weights
pc_loss_weight: 3.0
img_loss_weight: 1.0
fuse_loss_weight: 3.0
leading_loss: false
lead_loss_weight: 0.15
leading_class_weights: false
weighted_loss: false

# Model architecture
emb_dims: 768
num_points: 7168
encoder: b                      # Options: s, b, l, xl
fusion_dim: 128
dp_fuse: 0.5
dp_pc: 0.5
use_mf: false
spatial_attention: true
use_residual: false
mamba_fuse: false
fuse_feature: true
linear_layers_dims: [512, 256]

# Data transforms
image_transform: compose        # Options: compose, random, None
point_cloud_transform: true
rotate: false

# Hardware
gpus: 1
