# config_rmf.yaml

# General
dataset: rmf_sp                        # Options: rmf, rmf_sp
tile_size: 128
n_bands: 9
class_weights: [0.134, 0.024, 0.055, 0.044, 0.025, 0.032, 0.261, 0.006, 0.420]
class_names: ["BF", "BW", "CE", "LA", "PT", "PJ", "PO", "SB", "SW"]
n_classes: 9
season_map: ["img_s2_spring", "img_s2_summer", "img_s2_fall", "img_s2_winter"]
img_mean: [127.01, 141.89, 127.91, 144.28, 155.25, 155.67, 152.29, 147.12, 157.88]
img_std: [73.04, 69.87, 64.70, 62.85, 54.15, 51.63, 48.04, 48.44, 50.08]

# Training parameters
task: regression
head:  fuse_head # Options: no_pc_head, fuse_head, all_head, no_img_head
pretrained_ckpt: None
batch_size: 64
max_epochs: 15
optimizer: adamW                 # Options: adam, adamW, sgd
scheduler: cosine         # Options: plateau, steplr, asha, cosine, cosinewarmup
lr: 0.0001
patience: 10
step_size: 10
momentum: 0.9
weight_decay: 0.0001

# Loss weights
weighted_loss: false
multitasks_uncertain_loss: false
loss_func: mse

# Model architecture
network: ResUnet
emb_dims: 768
num_points: 7168
encoder: b                      # Options: s, b, l, xl
fusion_dim: 128
dp_fuse: 0.5
dp_pc: 0.5
use_ms: true
linear_layers_dims: [512, 256]

# Data transforms
image_transform: compose
point_cloud_transform: true
rotate: false

# Hardware
gpus: 4